// <auto-generated />
namespace MACPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AdvancedAvatarSupport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdvancedAvatarSupport));
        
        string IMigrationMetadata.Id
        {
            get { return "201401230136275_AdvancedAvatarSupport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
