// <auto-generated />
namespace MACPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class BrokerTypeForAllEmployees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BrokerTypeForAllEmployees));
        
        string IMigrationMetadata.Id
        {
            get { return "201406112059052_BrokerTypeForAllEmployees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
